package main

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

func findTheDifference(s string, t string) byte {
	charCountMap := make([]int, 26)
	for i := 0; i < len(s); i++ {
		charCountMap[s[i]-'a']++
	}
	for i := 0; i < len(t); i++ {
		charCountMap[t[i]-'a']--
		if charCountMap[t[i]-'a'] < 0 {
			return t[i]
		}
	}
	return 0
}

// XOR
func findTheDifference2(s string, t string) byte {
	result := byte(0)
	for i := 0; i < len(s); i++ {
		result ^= s[i]
	}
	for i := 0; i < len(t); i++ {
		result ^= t[i]
	}
	return result
}

func findTheDifference3(s string, t string) byte {
	result := t[len(t)-1]
	for i := 0; i < len(s); i++ {
		result ^= s[i]
		result ^= t[i]
	}
	return result
}

// sum up bytes for two string and get difference
func findTheDifference4(s string, t string) byte {
	byteSumS, byteSumT := 0, 0
	for i := 0; i < len(s); i++ {
		byteSumS += int(s[i])
	}
	for i := 0; i < len(t); i++ {
		byteSumT += int(t[i])
	}
	return byte(byteSumT - byteSumS)
}

// sum up bytes for two string and get difference
func findTheDifference5(s string, t string) byte {
	byteSumS, byteSumT := 0, 0
	for i := 0; i < len(s); i++ {
		byteSumS += int(s[i])
		byteSumT += int(t[i])
	}
	return byte(byteSumT + int(t[len(t)-1]) - byteSumS)
}

func main() {

}
